### ISSUE TITLE
Image does not show up

### ISSUE THREAD

**Issue by benjaminwnelson** [Timag/imageclipr#10]
Thanks for making this package!

I was able to follow all instructions, but once the code is pasted into R the image does now show up. Any ideas?

**Comment by Toniiiio** [comment]
HI @benjaminwnelson,

does it show up if you put the focus of the mouse to the name of the picture and "click" (e.g. "clipboardimage_1.png") within the code?

See the end of the gif here:
https://github.com/Toniiiio/imageclipr/blob/master/usage.gif


Thats a strange workaround, but somehow it seems to trigger the relevant update within RStudio. If that doesnt help please help me by secifying at which step it fails.
Is the picture present in the folder? 
Is the picture loaded if you manually insert the (same) code?

Thanks,
Tonio
