### ISSUE TITLE
Shortcut key

### ISSUE THREAD

**Issue by danielmlow** [Timag/imageclipr#11]
Thanks for the package!

I recently installed this and the shortcut key is no longer "InsertImage" but rather "Paste Img to Rmd file". Could you change this in the README? 

![image](https://user-images.githubusercontent.com/14787791/110345059-2be75880-7ffc-11eb-9bc6-a747c0f9a1dd.png)

As the package also appears differently in the Addin tab, so might want to change the image for that as well in the README. 

![image](https://user-images.githubusercontent.com/14787791/110345277-63ee9b80-7ffc-11eb-9bce-495e2579247c.png)

**Comment by Toniiiio** [comment]
Thanks for finding Daniel. I added a small note in the addin until i find the time to update the screenshots. PRs are welcome of course.
Tonio
