### ISSUE TITLE
Error : (converted from warning) unable to re-encode 'insertImageCode.R' line 26

### ISSUE THREAD

**Issue by kmcbest** [Timag/imageclipr#8]
Hello, I've tried devtools::install_github('Timag/imageclipr') and got this error:
> Error : (converted from warning) unable to re-encode 'insertImageCode.R' line 26

I've analyzed the line
`write (the clipboard as «class PNGf») to theFile`

It seems the «» is the culpable. I forked and removed them, and it installed fine.

**Comment by Toniiiio** [comment]
Thank you for your feedback.
Could you share your `sessionInfo()` including your OS please?

That line is from a commit of @xiaoa6435 . It is for adding Mac OS support. If you remove it and it works fine my guess is you are not on MAC. 

According to https://r.789695.n4.nabble.com/Error-on-Windows-build-unable-to-re-encode-tp1570626p1570643.html it could be worth a try to add a default encoding to the description file. I would probably go for UTF-8, but i am unsure about the Linux and MAC support. Maybe @xiaoa6435  could give his view on that line.

**Comment by kmcbest** [comment]
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2    yaml_2.2.1    


I just removed the non-ascII characters « and », and it works. I think it's just cosmetic and they can be replaced by simply putting quotation marks like "class PNGf".
